// app/components/Navbar.jsx
import { SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

export default function Navbar() {
  return (
    <div className="flex justify-between p-5 m-5 bg-purple rounded-2xl">
      <h1 className="text-2xl font-bold">teker</h1>
      <div>
        <SignedIn>
          <UserButton />
        </SignedIn>
        <SignedOut>
          <SignInButton />
        </SignedOut>
      </div>
    </div>
  );
}

// src/lib/components/nav/Navbar.svelte
<script>
	import { userStore } from '$lib/stores/user';
</script>

<div class="flex justify-between p-3">
	<div>
		<h1 class="text-2xl font-bold">Teker</h1>
	</div>
	<div>
		{#if $userStore}
			<a href="/profile" class="">Profile</a>
		{:else}
			<a href="/login" class="">Login</a>
		{/if}
	</div>
</div>
